name: CI Pipeline NodeJS e Jest

on:
  push:
    branches:
      - main
      - dev
      - hml

jobs:
  build-test-artefato-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v4

      - name: Configurar o NodeJS 20.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.0

      - name: Instala as Dependências
        run: npm install

      - name: Executa os Testes
        run: npm test

      - name: Build do Projeto
        run: npm run build

      - name: Upload dos Artefatos
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/

  build-hml:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/hml'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install