name: Pipeline do Ambiente de Produção

on:
    push:
      branches:
        - main

deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production

jobs:
  build-test-artefato-producao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v4

      - name: Configurar o NodeJS 20.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.0

      - name: Instala as Dependências
        run: npm install

      - name: Build do Projeto
        run: npm run build

      - name: Executa os Testes
        run: npm test

      - name: Upload dos Artefatos
        uses: actions/upload-artifact@v4
        with:
          name: Local dos Artefatos
          path: dist/